### ISSUE TITLE
HTC VIVE PRO EYE use GazeParser？

### ISSUE THREAD

**Issue by JackieQiang** [hsogo/gazeparser#1]
I am using a VR headset (HTC VIVE PRO EYE) to record eye tracking data. I would like to know if there is a way to use GazeParser to analyze HTC VIVE PRO EYE eye tracking data?
For example, can I convert eye tracking data recorded by HTC VIVE PRO EYE into SimpleGazeTracker CSV format?
Is there any relevant documentation or tutorials?

**Comment by hsogo** [comment]
Hi,
Because I don't know the output format of HTC VIVE PRO Eye, I'm not sure how can we convert the output to SimpleGazeTracker CSV format (or GazeParser datafile).  Could you please let me know if the is any documentation that describes the output format of HTC VIVE PRO EYE?

**Comment by JackieQiang** [comment]
Thank you for your quick reply.

I currently use HTC's official tool to record eye tracking data. See the image below for details of eye tracking data
![HTC_VIVE_PRO_EYE_Gaze_info](https://github.com/hsogo/gazeparser/assets/10878226/2b7b69c1-75b4-4fc4-b06d-e0b70339754f)

In my code, I collect these eye tracking data according to the frame rate I set and output a csv file, You can view the picture below.
<img width="1266" alt="567e45902b6e072478f13918a1e4225" src="https://github.com/hsogo/gazeparser/assets/10878226/f7f65884-0c02-4201-a5e2-ae87257d7a70">

**Comment by hsogo** [comment]
Thank you for the information.  GazeParser assumes that gaze location is represented by 2D coordinates on the monitor.  On the other hand, VIVE PRO EYE outputs gaze direction in the normalized 3D vector.  So, we have to convert 3D gaze directions to 2D screen coordinates to use GazePaser for data analysis.   What kind of are you planning to do with your data?  If you need 3D gaze locations, I don't think converting them to 2D is a good idea.

**Comment by JackieQiang** [comment]
Thank you very much for your reply.

I am planning to use my eye tracking data to analyze sentiment, as referenced in the VR Eyes Emotions Dataset (VREED) available at https://www.kaggle.com/datasets/lumaatabbaa/vr-eyes-emotions-dataset-vreed. Currently, I am attempting to convert 3D gaze directions into 2D screen coordinates, but I have two questions:

1.Do you know of any methods to convert 3D gaze directions into 2D screen coordinates?
2.Once I obtain 2D screen coordinates, how can I convert them into the SimpleGazeTracker CSV format?

PS:I found this page https://gazeparser.sourceforge.net/rec/sampledata.html#format-of-the-simplegazetracker-csv-data-file-0-8-0, but it seems not to provide a complete example of the SimpleGazeTracker CSV file.

**Comment by hsogo** [comment]
Let $G=(g_x,g_y,g_z)$ be the gaze vector, and $E=(e_x,e_y,e_z)$ be the eye center.  The point on the line passing through $E$ and parallel to $G$ is $E+tG$ ($t$ is a parameter).  On the other hand, A plane contains $(s_x, s_y, s_z)$ and normal to $(n_x, n_y, n_z)$ is $n_x(x-s_x)+n_y(y-s_y)+n_z(z-s_z)=0$.  The gaze point on the plane can be calculated from these.

A sample of SimpleGazeTracker CSV format is as follows.  The first 3 lines are required.  `#DATAFORMAT` defines what each column represents in the data session.
- T: timestamp
- LX, LY: gaze point of the left eye
- RX, RY: gaze point of the right eye
- LP: RP: pupil size of the left and right eye
The lines from the 4th to the line before `#START_REC` are conversion parameters.  Please see https://gazeparser.sourceforge.net/cnf/ConfigGazeParser.html for these parameters.
`#START_REC` represents the beginning of a data session. `#START_REC` requires the recording date (any date is OK).  The recorded data are lines between `#START_REC` and `#STOP_REC`. 
```
#SimpleGazeTrackerDataFile
#TRACKER_VERSION,0.12.0
#DATAFORMAT,T,LX,LY,RX,RY,LP,RP
#SACCADE_MINIMUM_DURATION,12
#SACCADE_ACCELERATION_THRESHOLD,3800.0
#SCREEN_WIDTH,1920
#FILTER_WN,0.5
#DOTS_PER_CENTIMETER_H,37.7
#TRACKER_ORIGIN,BottomLeft
#RECORDED_EYE,B
#FILTER_ORDER,3
#BLINK_MINIMUM_DURATION,50
#FILTER_SIZE,5
#FILTER_TYPE,identity
#DOTS_PER_CENTIMETER_V,37.7
#VIEWING_DISTANCE,57.2957795131
#SACCADE_VELOCITY_THRESHOLD,30.0
#SCREEN_ORIGIN,BottomLeft
#FIXATION_MINIMUM_DURATION,12
#SCREEN_HEIGHT,1080
#START_REC,2023,11,30,00,00,00
0.000,997.0,529.1,949.0,541.4,140.4,140.7
2.095,989.3,535.0,946.0,550.1,140.7,140.8
6.979,992.6,537.1,928.1,550.6,137.9,138.1
12.023,993.0,531.9,929.7,545.9,139.1,139.5
17.102,994.5,529.4,929.1,545.7,139.1,138.9
22.106,1004.7,518.3,931.4,573.1,142.3,137.4
27.107,1002.0,525.6,933.9,568.8,140.9,138.9
32.146,1005.9,515.5,938.4,574.3,143.7,137.3
37.109,1007.0,542.0,930.6,566.5,137.9,137.4
42.106,995.3,523.6,935.9,557.6,139.3,137.8
#STOP_REC
#START_REC,2023,11,30,00,01,00
0.000,969.9,491.7,953.7,544.9,174.8,161.4
4.256,975.7,497.8,966.5,548.9,172.9,162.6
9.250,966.6,530.0,962.6,545.8,174.0,162.9
14.157,960.3,529.9,960.0,544.4,173.1,163.8
19.215,967.4,489.8,956.7,540.1,177.6,163.8
24.206,961.3,517.7,957.5,532.8,173.0,165.8
29.206,962.2,510.7,950.4,542.8,180.0,165.1
34.208,957.7,508.0,959.5,562.3,176.0,163.4
39.211,960.4,516.8,949.9,554.5,175.9,163.9
#STOP_REC
```

**Comment by JackieQiang** [comment]
Thank you very much for your answer. 
These are exactly what I need. 
GazeParser is now available 👍
